// <auto-generated> by tools/gen_combinators.cs. Do not edit by hand. </auto-generated>
namespace Katout.FlowTask.Internal;

internal sealed class RaceNode<T0, T1> : RaceNodeBase<RaceResult<T0, T1>>
{
    static NodePool<RaceNode<T0, T1>> s_pool;

    internal static RaceNode<T0, T1> Rent()
    {
        var n = s_pool.Rent() ?? new RaceNode<T0, T1>();
        n.InitUnstarted();
        return n;
    }

    internal override string Name => "Race";

    protected override RaceResult<T0, T1> BuildResult(int index) => new RaceResult<T0, T1>(index, index == 0 ? ((FlowNode<T0>)Branches[0].Node).Result : default, index == 1 ? ((FlowNode<T1>)Branches[1].Node).Result : default);

    protected override void ReturnToPool() => s_pool.Return(this);
}

internal sealed class WhenAllNode<T1, T2> : WhenAllNodeBase<(T1, T2)>
{
    static NodePool<WhenAllNode<T1, T2>> s_pool;

    internal static WhenAllNode<T1, T2> Rent()
    {
        var n = s_pool.Rent() ?? new WhenAllNode<T1, T2>();
        n.InitUnstarted();
        return n;
    }

    internal override string Name => "WhenAll";

    protected override (T1, T2) BuildResult() => (((FlowNode<T1>)Branches[0].Node).Result, ((FlowNode<T2>)Branches[1].Node).Result);

    protected override void ReturnToPool() => s_pool.Return(this);
}

internal sealed class RaceNode<T0, T1, T2> : RaceNodeBase<RaceResult<T0, T1, T2>>
{
    static NodePool<RaceNode<T0, T1, T2>> s_pool;

    internal static RaceNode<T0, T1, T2> Rent()
    {
        var n = s_pool.Rent() ?? new RaceNode<T0, T1, T2>();
        n.InitUnstarted();
        return n;
    }

    internal override string Name => "Race";

    protected override RaceResult<T0, T1, T2> BuildResult(int index) => new RaceResult<T0, T1, T2>(index, index == 0 ? ((FlowNode<T0>)Branches[0].Node).Result : default, index == 1 ? ((FlowNode<T1>)Branches[1].Node).Result : default, index == 2 ? ((FlowNode<T2>)Branches[2].Node).Result : default);

    protected override void ReturnToPool() => s_pool.Return(this);
}

internal sealed class WhenAllNode<T1, T2, T3> : WhenAllNodeBase<(T1, T2, T3)>
{
    static NodePool<WhenAllNode<T1, T2, T3>> s_pool;

    internal static WhenAllNode<T1, T2, T3> Rent()
    {
        var n = s_pool.Rent() ?? new WhenAllNode<T1, T2, T3>();
        n.InitUnstarted();
        return n;
    }

    internal override string Name => "WhenAll";

    protected override (T1, T2, T3) BuildResult() => (((FlowNode<T1>)Branches[0].Node).Result, ((FlowNode<T2>)Branches[1].Node).Result, ((FlowNode<T3>)Branches[2].Node).Result);

    protected override void ReturnToPool() => s_pool.Return(this);
}
