// <auto-generated> by tools/gen_combinators.cs. Do not edit by hand. </auto-generated>
namespace Katout.FlowTask;

public readonly partial struct FlowTask
{
    /// <summary>
    /// Returns the first branch to complete, with its index and value; the other branches are canceled and unwound (their
    /// finally blocks run to their end) before the caller resumes. A branch that throws first ends the Race as in WhenAll.
    /// </summary>
    /// <remarks>
    /// The branches start in argument order, each up to its first wait, and one that completes as it starts wins at once.
    /// Branches that complete in the same flush win in the order they are processed (time waits satisfied by one Tick, in the
    /// order they began), so put an event before the work it interrupts: <c>Race(hits.Next(), Patrol())</c>. A value that a
    /// losing wait on a <see cref="Subscription{T}"/> already received goes back to the subscription. For a timeout, race the
    /// work against <see cref="WaitForSeconds"/>.
    /// </remarks>
    public static FlowTask<RaceResult<FlowUnit, FlowUnit>> Race(FlowTask t0, FlowTask t1)
    {
        Flow.CheckStartable<FlowUnit>(t0);
        Flow.CheckStartable<FlowUnit>(t1);
        var n = RaceNode<FlowUnit, FlowUnit>.Rent();
        n.AddBranch(Flow.Materialize<FlowUnit>(t0));
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        return new FlowTask<RaceResult<FlowUnit, FlowUnit>>(n, n.Token);
    }

    /// <summary>
    /// Waits for every branch. With a branch that has a value, the result is a tuple of the branches' values in order
    /// (<see cref="FlowUnit"/> for a branch without one); with none, it is a FlowTask. When one throws, the others are
    /// canceled and unwound before the exception is thrown at the await (Task.WhenAll lets them run on).
    /// </summary>
    public static FlowTask WhenAll(FlowTask t1, FlowTask t2)
    {
        Flow.CheckStartable<FlowUnit>(t1);
        Flow.CheckStartable<FlowUnit>(t2);
        var n = WhenAllVoidNode.Rent(2);
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        n.AddBranch(Flow.Materialize<FlowUnit>(t2));
        return new FlowTask(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<FlowUnit, T1>> Race<T1>(FlowTask t0, FlowTask<T1> t1)
    {
        Flow.CheckStartable<FlowUnit>(t0);
        Flow.CheckStartable(t1);
        var n = RaceNode<FlowUnit, T1>.Rent();
        n.AddBranch(Flow.Materialize<FlowUnit>(t0));
        n.AddBranch(Flow.Materialize(t1));
        return new FlowTask<RaceResult<FlowUnit, T1>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask<(FlowUnit, T2)> WhenAll<T2>(FlowTask t1, FlowTask<T2> t2)
    {
        Flow.CheckStartable<FlowUnit>(t1);
        Flow.CheckStartable(t2);
        var n = WhenAllNode<FlowUnit, T2>.Rent();
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        n.AddBranch(Flow.Materialize(t2));
        return new FlowTask<(FlowUnit, T2)>(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<T0, FlowUnit>> Race<T0>(FlowTask<T0> t0, FlowTask t1)
    {
        Flow.CheckStartable(t0);
        Flow.CheckStartable<FlowUnit>(t1);
        var n = RaceNode<T0, FlowUnit>.Rent();
        n.AddBranch(Flow.Materialize(t0));
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        return new FlowTask<RaceResult<T0, FlowUnit>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask<(T1, FlowUnit)> WhenAll<T1>(FlowTask<T1> t1, FlowTask t2)
    {
        Flow.CheckStartable(t1);
        Flow.CheckStartable<FlowUnit>(t2);
        var n = WhenAllNode<T1, FlowUnit>.Rent();
        n.AddBranch(Flow.Materialize(t1));
        n.AddBranch(Flow.Materialize<FlowUnit>(t2));
        return new FlowTask<(T1, FlowUnit)>(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<T0, T1>> Race<T0, T1>(FlowTask<T0> t0, FlowTask<T1> t1)
    {
        Flow.CheckStartable(t0);
        Flow.CheckStartable(t1);
        var n = RaceNode<T0, T1>.Rent();
        n.AddBranch(Flow.Materialize(t0));
        n.AddBranch(Flow.Materialize(t1));
        return new FlowTask<RaceResult<T0, T1>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask<(T1, T2)> WhenAll<T1, T2>(FlowTask<T1> t1, FlowTask<T2> t2)
    {
        Flow.CheckStartable(t1);
        Flow.CheckStartable(t2);
        var n = WhenAllNode<T1, T2>.Rent();
        n.AddBranch(Flow.Materialize(t1));
        n.AddBranch(Flow.Materialize(t2));
        return new FlowTask<(T1, T2)>(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<FlowUnit, FlowUnit, FlowUnit>> Race(FlowTask t0, FlowTask t1, FlowTask t2)
    {
        Flow.CheckStartable<FlowUnit>(t0);
        Flow.CheckStartable<FlowUnit>(t1);
        Flow.CheckStartable<FlowUnit>(t2);
        var n = RaceNode<FlowUnit, FlowUnit, FlowUnit>.Rent();
        n.AddBranch(Flow.Materialize<FlowUnit>(t0));
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        n.AddBranch(Flow.Materialize<FlowUnit>(t2));
        return new FlowTask<RaceResult<FlowUnit, FlowUnit, FlowUnit>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask WhenAll(FlowTask t1, FlowTask t2, FlowTask t3)
    {
        Flow.CheckStartable<FlowUnit>(t1);
        Flow.CheckStartable<FlowUnit>(t2);
        Flow.CheckStartable<FlowUnit>(t3);
        var n = WhenAllVoidNode.Rent(3);
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        n.AddBranch(Flow.Materialize<FlowUnit>(t2));
        n.AddBranch(Flow.Materialize<FlowUnit>(t3));
        return new FlowTask(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<FlowUnit, FlowUnit, T2>> Race<T2>(FlowTask t0, FlowTask t1, FlowTask<T2> t2)
    {
        Flow.CheckStartable<FlowUnit>(t0);
        Flow.CheckStartable<FlowUnit>(t1);
        Flow.CheckStartable(t2);
        var n = RaceNode<FlowUnit, FlowUnit, T2>.Rent();
        n.AddBranch(Flow.Materialize<FlowUnit>(t0));
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        n.AddBranch(Flow.Materialize(t2));
        return new FlowTask<RaceResult<FlowUnit, FlowUnit, T2>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask<(FlowUnit, FlowUnit, T3)> WhenAll<T3>(FlowTask t1, FlowTask t2, FlowTask<T3> t3)
    {
        Flow.CheckStartable<FlowUnit>(t1);
        Flow.CheckStartable<FlowUnit>(t2);
        Flow.CheckStartable(t3);
        var n = WhenAllNode<FlowUnit, FlowUnit, T3>.Rent();
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        n.AddBranch(Flow.Materialize<FlowUnit>(t2));
        n.AddBranch(Flow.Materialize(t3));
        return new FlowTask<(FlowUnit, FlowUnit, T3)>(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<FlowUnit, T1, FlowUnit>> Race<T1>(FlowTask t0, FlowTask<T1> t1, FlowTask t2)
    {
        Flow.CheckStartable<FlowUnit>(t0);
        Flow.CheckStartable(t1);
        Flow.CheckStartable<FlowUnit>(t2);
        var n = RaceNode<FlowUnit, T1, FlowUnit>.Rent();
        n.AddBranch(Flow.Materialize<FlowUnit>(t0));
        n.AddBranch(Flow.Materialize(t1));
        n.AddBranch(Flow.Materialize<FlowUnit>(t2));
        return new FlowTask<RaceResult<FlowUnit, T1, FlowUnit>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask<(FlowUnit, T2, FlowUnit)> WhenAll<T2>(FlowTask t1, FlowTask<T2> t2, FlowTask t3)
    {
        Flow.CheckStartable<FlowUnit>(t1);
        Flow.CheckStartable(t2);
        Flow.CheckStartable<FlowUnit>(t3);
        var n = WhenAllNode<FlowUnit, T2, FlowUnit>.Rent();
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        n.AddBranch(Flow.Materialize(t2));
        n.AddBranch(Flow.Materialize<FlowUnit>(t3));
        return new FlowTask<(FlowUnit, T2, FlowUnit)>(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<FlowUnit, T1, T2>> Race<T1, T2>(FlowTask t0, FlowTask<T1> t1, FlowTask<T2> t2)
    {
        Flow.CheckStartable<FlowUnit>(t0);
        Flow.CheckStartable(t1);
        Flow.CheckStartable(t2);
        var n = RaceNode<FlowUnit, T1, T2>.Rent();
        n.AddBranch(Flow.Materialize<FlowUnit>(t0));
        n.AddBranch(Flow.Materialize(t1));
        n.AddBranch(Flow.Materialize(t2));
        return new FlowTask<RaceResult<FlowUnit, T1, T2>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask<(FlowUnit, T2, T3)> WhenAll<T2, T3>(FlowTask t1, FlowTask<T2> t2, FlowTask<T3> t3)
    {
        Flow.CheckStartable<FlowUnit>(t1);
        Flow.CheckStartable(t2);
        Flow.CheckStartable(t3);
        var n = WhenAllNode<FlowUnit, T2, T3>.Rent();
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        n.AddBranch(Flow.Materialize(t2));
        n.AddBranch(Flow.Materialize(t3));
        return new FlowTask<(FlowUnit, T2, T3)>(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<T0, FlowUnit, FlowUnit>> Race<T0>(FlowTask<T0> t0, FlowTask t1, FlowTask t2)
    {
        Flow.CheckStartable(t0);
        Flow.CheckStartable<FlowUnit>(t1);
        Flow.CheckStartable<FlowUnit>(t2);
        var n = RaceNode<T0, FlowUnit, FlowUnit>.Rent();
        n.AddBranch(Flow.Materialize(t0));
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        n.AddBranch(Flow.Materialize<FlowUnit>(t2));
        return new FlowTask<RaceResult<T0, FlowUnit, FlowUnit>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask<(T1, FlowUnit, FlowUnit)> WhenAll<T1>(FlowTask<T1> t1, FlowTask t2, FlowTask t3)
    {
        Flow.CheckStartable(t1);
        Flow.CheckStartable<FlowUnit>(t2);
        Flow.CheckStartable<FlowUnit>(t3);
        var n = WhenAllNode<T1, FlowUnit, FlowUnit>.Rent();
        n.AddBranch(Flow.Materialize(t1));
        n.AddBranch(Flow.Materialize<FlowUnit>(t2));
        n.AddBranch(Flow.Materialize<FlowUnit>(t3));
        return new FlowTask<(T1, FlowUnit, FlowUnit)>(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<T0, FlowUnit, T2>> Race<T0, T2>(FlowTask<T0> t0, FlowTask t1, FlowTask<T2> t2)
    {
        Flow.CheckStartable(t0);
        Flow.CheckStartable<FlowUnit>(t1);
        Flow.CheckStartable(t2);
        var n = RaceNode<T0, FlowUnit, T2>.Rent();
        n.AddBranch(Flow.Materialize(t0));
        n.AddBranch(Flow.Materialize<FlowUnit>(t1));
        n.AddBranch(Flow.Materialize(t2));
        return new FlowTask<RaceResult<T0, FlowUnit, T2>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask<(T1, FlowUnit, T3)> WhenAll<T1, T3>(FlowTask<T1> t1, FlowTask t2, FlowTask<T3> t3)
    {
        Flow.CheckStartable(t1);
        Flow.CheckStartable<FlowUnit>(t2);
        Flow.CheckStartable(t3);
        var n = WhenAllNode<T1, FlowUnit, T3>.Rent();
        n.AddBranch(Flow.Materialize(t1));
        n.AddBranch(Flow.Materialize<FlowUnit>(t2));
        n.AddBranch(Flow.Materialize(t3));
        return new FlowTask<(T1, FlowUnit, T3)>(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<T0, T1, FlowUnit>> Race<T0, T1>(FlowTask<T0> t0, FlowTask<T1> t1, FlowTask t2)
    {
        Flow.CheckStartable(t0);
        Flow.CheckStartable(t1);
        Flow.CheckStartable<FlowUnit>(t2);
        var n = RaceNode<T0, T1, FlowUnit>.Rent();
        n.AddBranch(Flow.Materialize(t0));
        n.AddBranch(Flow.Materialize(t1));
        n.AddBranch(Flow.Materialize<FlowUnit>(t2));
        return new FlowTask<RaceResult<T0, T1, FlowUnit>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask<(T1, T2, FlowUnit)> WhenAll<T1, T2>(FlowTask<T1> t1, FlowTask<T2> t2, FlowTask t3)
    {
        Flow.CheckStartable(t1);
        Flow.CheckStartable(t2);
        Flow.CheckStartable<FlowUnit>(t3);
        var n = WhenAllNode<T1, T2, FlowUnit>.Rent();
        n.AddBranch(Flow.Materialize(t1));
        n.AddBranch(Flow.Materialize(t2));
        n.AddBranch(Flow.Materialize<FlowUnit>(t3));
        return new FlowTask<(T1, T2, FlowUnit)>(n, n.Token);
    }

    /// <inheritdoc cref="Race(FlowTask, FlowTask)"/>
    public static FlowTask<RaceResult<T0, T1, T2>> Race<T0, T1, T2>(FlowTask<T0> t0, FlowTask<T1> t1, FlowTask<T2> t2)
    {
        Flow.CheckStartable(t0);
        Flow.CheckStartable(t1);
        Flow.CheckStartable(t2);
        var n = RaceNode<T0, T1, T2>.Rent();
        n.AddBranch(Flow.Materialize(t0));
        n.AddBranch(Flow.Materialize(t1));
        n.AddBranch(Flow.Materialize(t2));
        return new FlowTask<RaceResult<T0, T1, T2>>(n, n.Token);
    }

    /// <inheritdoc cref="WhenAll(FlowTask, FlowTask)"/>
    public static FlowTask<(T1, T2, T3)> WhenAll<T1, T2, T3>(FlowTask<T1> t1, FlowTask<T2> t2, FlowTask<T3> t3)
    {
        Flow.CheckStartable(t1);
        Flow.CheckStartable(t2);
        Flow.CheckStartable(t3);
        var n = WhenAllNode<T1, T2, T3>.Rent();
        n.AddBranch(Flow.Materialize(t1));
        n.AddBranch(Flow.Materialize(t2));
        n.AddBranch(Flow.Materialize(t3));
        return new FlowTask<(T1, T2, T3)>(n, n.Token);
    }

}

/// <summary>Winner of a 2-branch race: <see cref="Index"/> is the 0-based branch that completed first.</summary>
public readonly struct RaceResult<T0, T1>
{
    readonly T0 _v0;
    readonly T1 _v1;

    internal RaceResult(int index, T0 v0, T1 v1)
    {
        Index = index;
        _v0 = v0;
        _v1 = v1;
    }

    /// <summary>0-based index of the winning branch.</summary>
    public int Index { get; }

    /// <summary>True when branch 0 won; its value is returned in <paramref name="value"/>.</summary>
    public bool TryGet0(out T0 value)
    {
        value = _v0;
        return Index == 0;
    }

    /// <summary>Value of branch 0. Throws when another branch won.</summary>
    public T0 Value0 => Index == 0 ? _v0 : throw new System.InvalidOperationException($"Branch 0 did not win (winner: {Index}).");

    /// <summary>True when branch 1 won; its value is returned in <paramref name="value"/>.</summary>
    public bool TryGet1(out T1 value)
    {
        value = _v1;
        return Index == 1;
    }

    /// <summary>Value of branch 1. Throws when another branch won.</summary>
    public T1 Value1 => Index == 1 ? _v1 : throw new System.InvalidOperationException($"Branch 1 did not win (winner: {Index}).");

    /// <summary><c>Race[index] = value</c> of the winner.</summary>
    public override string ToString() => Index switch
    {
        0 => $"Race[0] = {_v0}",
        1 => $"Race[1] = {_v1}",
        _ => "Race[?]",
    };
}

/// <summary>Winner of a 3-branch race: <see cref="Index"/> is the 0-based branch that completed first.</summary>
public readonly struct RaceResult<T0, T1, T2>
{
    readonly T0 _v0;
    readonly T1 _v1;
    readonly T2 _v2;

    internal RaceResult(int index, T0 v0, T1 v1, T2 v2)
    {
        Index = index;
        _v0 = v0;
        _v1 = v1;
        _v2 = v2;
    }

    /// <summary>0-based index of the winning branch.</summary>
    public int Index { get; }

    /// <summary>True when branch 0 won; its value is returned in <paramref name="value"/>.</summary>
    public bool TryGet0(out T0 value)
    {
        value = _v0;
        return Index == 0;
    }

    /// <summary>Value of branch 0. Throws when another branch won.</summary>
    public T0 Value0 => Index == 0 ? _v0 : throw new System.InvalidOperationException($"Branch 0 did not win (winner: {Index}).");

    /// <summary>True when branch 1 won; its value is returned in <paramref name="value"/>.</summary>
    public bool TryGet1(out T1 value)
    {
        value = _v1;
        return Index == 1;
    }

    /// <summary>Value of branch 1. Throws when another branch won.</summary>
    public T1 Value1 => Index == 1 ? _v1 : throw new System.InvalidOperationException($"Branch 1 did not win (winner: {Index}).");

    /// <summary>True when branch 2 won; its value is returned in <paramref name="value"/>.</summary>
    public bool TryGet2(out T2 value)
    {
        value = _v2;
        return Index == 2;
    }

    /// <summary>Value of branch 2. Throws when another branch won.</summary>
    public T2 Value2 => Index == 2 ? _v2 : throw new System.InvalidOperationException($"Branch 2 did not win (winner: {Index}).");

    /// <summary><c>Race[index] = value</c> of the winner.</summary>
    public override string ToString() => Index switch
    {
        0 => $"Race[0] = {_v0}",
        1 => $"Race[1] = {_v1}",
        2 => $"Race[2] = {_v2}",
        _ => "Race[?]",
    };
}
